package main;
import org.junit.Test;

import main.Main;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sim' at '10/20/16 7:30 PM' with Gradle 2.14.1
 *
 * @author sim, @date 10/20/16 7:30 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
